services:
  db:
    image: mysql:8.0
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/test_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8083:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-net

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-net

volumes:
  db-data:

networks:
  app-net:
